polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>", views.detail, name="detail"),
    path("<int:question_id>", views.results, name="results")
]

pollster/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=150, default="what is")
    pub_date = models.DateTimeField(default="date published")

    # def __str__(self):
    #     return self.question_text
        

class Choice(models.Model):
    question = models.ForeignKey(Question, default=0, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=150, default="life or death")
    votes = models.IntegerField(default=0)

    # def __str__(self):
    #     return self.choice_text


class Boxer(models.Model):
    skill = models.CharField(max_length=100, default="gear second")
    weight = models.IntegerField(default=60)

    # def __str__(self):
    #     return self.skill

polls/views.py
from django.shortcuts import render

# Create your views here.

from.models import Question, Choice, Boxer

# get questions and display them

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, "polls/index.htm", context)

# show a specific question and choices
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question deos not exist")
    return render(request, 'polls/results.htm', { 'question': question })
    
# get question and display results
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.htm', { 'question', question })

templates/base.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" 
        href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css" 
        integrity="sha384-DhY6onE6f3zzKbjUPRc2hOzGAdEf4/Dz+WJwBvEYL/lkkIsI3ihufq9hk9K4lVoK" 
        crossorigin="anonymous"
    />
    <title>X-hunter {% block title %} {% endblock %}</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 m-auto">
                {% block content %} {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

templates/polls/index.htm
{% extends 'base.htm' %}

{% block content %}

<h1 class="text-center mb-3">Poll Questions</h1>
  {% if latest_question_list %}
    {% for question in latest_question_list %}
      <div class="card mb-3">
          <div class="card-body">
              <p class="lead">{{ question.question_text }}</p>
              <a 
              href="{% url 'polls:detail' question.id %}"
              class="btn btn-primary btn-sm">Vote now</a>
              <a 
              href="{% url 'polls:results' question.id %}"
              class="btn btn-success btn-sm">Results</a>
          </div>
      </div>
    {% endfor %}
  {% else %}
    <p>No Polls availble</p>
  {% endif %}

{% endblock %}